### ISSUE TITLE
Schema files missing in distribution

### ISSUE THREAD

**Issue by misja** [johnnoone/json-spec#12]
I didn't notice this earlier but it appears schema files are missing from the distributed pypi files. 0.9.11 still seems to be ok but e.g. the 0.9.15 wheel doesn't include them. The source package does, but they  apparently do not get installed - somewhere the setup changed which causes it to miss the includes in the manifest?

**Comment by johnnoone** [comment]
exact, I don't know why wheel package does not include files that are declared in Manifest.in.
I've just pushed a 0.9.16 release, tell me if it works as expected.

**Comment by misja** [comment]
Can confirm the 0.9.16 wheel includes the schemas again. Noticed the `package_data` addition in `setup.py`, looks like that did the trick - thanks again.
