### ISSUE TITLE
PkgProvider not fully implemented

### ISSUE THREAD

**Issue by misja** [johnnoone/json-spec#7]
PkgProvider isn't fully implemented, missing `__iter__` and `__len__`, which makes it impossible to pass to the validator Factory. My question is if this was done on purpose, encouraging to subclass and implement or if a pull request would be appreciated?

**Comment by johnnoone** [comment]
It's a forgetting. I've pushed a new package to pypi (https://pypi.python.org/pypi/json-spec/0.9.13a1).
Can you try it and tell me if it's working? In which I will release a stable one.

**Comment by misja** [comment]
Perfect, thanks - can confirm it's working :)

**Comment by johnnoone** [comment]
https://pypi.python.org/pypi/json-spec/0.9.13 has been released.
